# -*- coding: utf-8 -*-
"""filtrodekalman017x-bucle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rlfm3CF74DBxjnzmdVz0eytrg1L02rDU
"""

#Cargando paquetes
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use('seaborn-darkgrid')
plt.rcParams['figure.figsize'] = (10,7)

#condiciones iniciales
A = np.array([1.07])
y = np.array([4000,4260, 4550, 4860, 5110])
n = len(y)
B = np.array([1])
u = np.full((n,1),1)
xp = np.array([[0.0]*1]*n)
x = np.array([[0.0]*1]*n)
xp[0] = y[0]
x[0] = y[0]
e0 = np.array([1])
p0 = np.diag(np.diag(np.outer(e0,e0)))
p = p0
pp = p
z0 = np.array([1])
r = np.diag(np.diag(np.outer(z0,z0)))

#iteraciones
for i in range(1,n):  
        j = i - 1
        xp[i] = A*x[j]+B*u[i]
        pp = A*p*A
        k = pp/(pp+r)
        ee = y[i]-xp[i]
        p = (1-k)*pp
        x[i] = xp[i]+k*ee

#para la variable1
plt.plot(xp)
plt.plot(x)
plt.plot(y)
plt.legend(['proyeccion', 'kalman', 'observado'])
plt.show()

#empaquetado final
#datos = np.concatenate((xp, x, y),axis=1)
#datos = pd.DataFrame(datos)
#datos.columns = ['proy1', 'proy2','kalman1','kalman2', 'obs1','obs2']